# Generated by Django 5.0.3 on 2024-07-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cajaKpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmacia', models.CharField(choices=[('FS01', 'FS01'), ('FS02', 'FS02'), ('FS03', 'FS03'), ('FS04', 'FS04'), ('FS05', 'FS05'), ('FS06', 'FS06'), ('FS07', 'FS07'), ('FS08', 'FS08'), ('FS09', 'FS09'), ('FS10', 'FS10'), ('FS11', 'FS11'), ('FS12', 'FS12'), ('FS13', 'FS13'), ('FS14', 'FS14'), ('FS15', 'FS15'), ('FS16', 'FS16'), ('FS17', 'FS17'), ('FS18', 'FS18'), ('FS19', 'FS19'), ('FS20', 'FS20'), ('FS21', 'FS21'), ('FS22', 'FS22'), ('FS23', 'FS23'), ('FS24', 'FS24'), ('FS25', 'FS25')], max_length=5)),
                ('legajo', models.PositiveIntegerField()),
                ('tarea', models.CharField(choices=[('Nota de credito', 'Nota de crédito'), ('Anulacion de temporales', 'Anulación de temporales'), ('Ecommerce Entrega', 'Ecommerce Entrega'), ('Ecommerce retirado', 'Ecommerce retirado'), ('Consumidor final', 'Consumidor final'), ('999999', '999999'), ('Diferencia de caja', 'Diferencia de caja')], max_length=50)),
                ('fecha', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('gestionado', models.CharField(choices=[('Si', 'Sí'), ('No', 'No')], max_length=2)),
            ],
        ),
    ]
