# Generated by Django 5.0.3 on 2024-07-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='expertasKpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmacia', models.CharField(choices=[('FS01', 'FS01'), ('FS02', 'FS02'), ('FS03', 'FS03'), ('FS04', 'FS04'), ('FS05', 'FS05'), ('FS06', 'FS06'), ('FS07', 'FS07'), ('FS08', 'FS08'), ('FS09', 'FS09'), ('FS10', 'FS10'), ('FS11', 'FS11'), ('FS12', 'FS12'), ('FS13', 'FS13'), ('FS14', 'FS14'), ('FS15', 'FS15'), ('FS16', 'FS16'), ('FS17', 'FS17'), ('FS18', 'FS18'), ('FS19', 'FS19'), ('FS20', 'FS20'), ('FS21', 'FS21'), ('FS22', 'FS22'), ('FS23', 'FS23'), ('FS24', 'FS24'), ('FS25', 'FS25')], max_length=5)),
                ('legajo', models.PositiveIntegerField()),
                ('tarea', models.CharField(choices=[('Vencidos', 'Vencidos'), ('Blotters', 'Blotters'), ('Ofertas', 'Ofertas'), ('Orden y limpieza', 'Orden y limpieza')], max_length=50)),
                ('fecha', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('gestionado', models.CharField(choices=[('Si', 'Sí'), ('No', 'No')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='stockKpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmacia', models.CharField(choices=[('FS01', 'FS01'), ('FS02', 'FS02'), ('FS03', 'FS03'), ('FS04', 'FS04'), ('FS05', 'FS05'), ('FS06', 'FS06'), ('FS07', 'FS07'), ('FS08', 'FS08'), ('FS09', 'FS09'), ('FS10', 'FS10'), ('FS11', 'FS11'), ('FS12', 'FS12'), ('FS13', 'FS13'), ('FS14', 'FS14'), ('FS15', 'FS15'), ('FS16', 'FS16'), ('FS17', 'FS17'), ('FS18', 'FS18'), ('FS19', 'FS19'), ('FS20', 'FS20'), ('FS21', 'FS21'), ('FS22', 'FS22'), ('FS23', 'FS23'), ('FS24', 'FS24'), ('FS25', 'FS25')], max_length=5)),
                ('legajo', models.PositiveIntegerField()),
                ('tarea', models.CharField(choices=[('Recepcion (tiempo)', 'Recepcion (tiempo)'), ('Compras(drog externa)', 'Compras(drog externa)'), ('Ajuste de stock', 'Ajuste de stock'), ('Negativos', 'Negativos'), ('Ecom cambio deestado', 'Ecom cambio de estado'), ('Revision GPS', 'Revision GPS'), ('Pedidos pendientes', 'Pedidos pendientes'), ('Vales', 'Vales')], max_length=50)),
                ('fecha', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('gestionado', models.CharField(choices=[('Si', 'Sí'), ('No', 'No')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='tradeKpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmacia', models.CharField(choices=[('FS01', 'FS01'), ('FS02', 'FS02'), ('FS03', 'FS03'), ('FS04', 'FS04'), ('FS05', 'FS05'), ('FS06', 'FS06'), ('FS07', 'FS07'), ('FS08', 'FS08'), ('FS09', 'FS09'), ('FS10', 'FS10'), ('FS11', 'FS11'), ('FS12', 'FS12'), ('FS13', 'FS13'), ('FS14', 'FS14'), ('FS15', 'FS15'), ('FS16', 'FS16'), ('FS17', 'FS17'), ('FS18', 'FS18'), ('FS19', 'FS19'), ('FS20', 'FS20'), ('FS21', 'FS21'), ('FS22', 'FS22'), ('FS23', 'FS23'), ('FS24', 'FS24'), ('FS25', 'FS25')], max_length=5)),
                ('legajo', models.PositiveIntegerField()),
                ('tarea', models.CharField(choices=[('Vencimientos', 'Vencimientos'), ('Señalizacion', 'Señalizacion'), ('Descuentos', 'Descuentos'), ('Mercaderia a disposicion', 'Mercaderia a disposicion'), ('Actualizacion', 'Actualizacion')], max_length=50)),
                ('fecha', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('gestionado', models.CharField(choices=[('Si', 'Sí'), ('No', 'No')], max_length=2)),
            ],
        ),
    ]
